# Generated by Django 5.2.7 on 2025-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count_watches',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
